### ISSUE TITLE
Release as an extension

### ISSUE THREAD

**Issue by buckleyGI** [natsusenpai/text-highlight-chrome#1]
Can you point me in the direction of packaging it up as an extension? I'll see if I can post these imprisonments to the chrome store as well as I have the need to tweak it a little more. Nice initiative to bring this good extensions to live 👍

**Comment by natsusenpai** [comment]
> Can you point me in the direction of packaging it up as an extension? I'll see if I can post these imprisonments to the chrome store as well as I have the need to tweak it a little more. Nice initiative to bring this good extensions to live 👍

Hey there, are you asking for the guide of using this locally? If it is what you are looking for then this might help you: https://superuser.com/questions/247651/how-does-one-install-an-extension-for-chrome-browser-from-the-local-file-system

**Comment by buckleyGI** [comment]
Thanks
